# Name : Jay Rambhiya

# Git-Hub Username : jay-rambhiya

# USC ID: #2219880371

In [1]:
# Import statements
import pandas as pd
import glob
import seaborn as sns
import numpy as np
from sklearn import metrics
from sklearn.metrics import accuracy_score
import math
from tabulate import tabulate
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split
import glob
import bootstrapped.bootstrap as bs
import bootstrapped.stats_functions as bs_stats
import numpy as np
import scipy.stats as st
from pathlib import Path
import os

In [2]:
dataPath = 'data/AReM/'

# 1. (b) Creating training and testing datasets

In [3]:
dir1 = ['bending1', 'bending2']
dir2 = ['cycling', 'lying', 'sitting', 'standing', 'walking']
trainCsvs, testCsvs, allCsvs = [], [], []
curr=[]

for d in dir1:
    for filename in os.listdir(dataPath+d):
        curr.append(dataPath+d+"/"+filename)
        if filename[-6:-4] in ('t1', 't2'):
            testCsvs.append(dataPath+d+"/"+filename)
        else:
            trainCsvs.append(dataPath+d+"/"+filename)
for d in dir2:
    for filename in os.listdir(dataPath+d):
        curr.append(dataPath+d+"/"+filename)
        if filename[-6:-4] in ('t1', 't2' , 't3'):
            testCsvs.append(dataPath+d+"/"+filename)
        else:
            trainCsvs.append(dataPath+d+"/"+filename)
curr.sort()
allCsvs.append(curr)

In [4]:
testCsvs

['data/AReM/bending1/dataset1.csv',
 'data/AReM/bending1/dataset2.csv',
 'data/AReM/bending2/dataset1.csv',
 'data/AReM/bending2/dataset2.csv',
 'data/AReM/cycling/dataset1.csv',
 'data/AReM/cycling/dataset2.csv',
 'data/AReM/cycling/dataset3.csv',
 'data/AReM/lying/dataset1.csv',
 'data/AReM/lying/dataset2.csv',
 'data/AReM/lying/dataset3.csv',
 'data/AReM/sitting/dataset1.csv',
 'data/AReM/sitting/dataset2.csv',
 'data/AReM/sitting/dataset3.csv',
 'data/AReM/standing/dataset1.csv',
 'data/AReM/standing/dataset2.csv',
 'data/AReM/standing/dataset3.csv',
 'data/AReM/walking/dataset1.csv',
 'data/AReM/walking/dataset2.csv',
 'data/AReM/walking/dataset3.csv']

In [5]:
 trainCsvs

['data/AReM/bending1/dataset7.csv',
 'data/AReM/bending1/dataset6.csv',
 'data/AReM/bending1/dataset4.csv',
 'data/AReM/bending1/dataset5.csv',
 'data/AReM/bending1/dataset3.csv',
 'data/AReM/bending2/dataset6.csv',
 'data/AReM/bending2/dataset4.csv',
 'data/AReM/bending2/dataset5.csv',
 'data/AReM/bending2/dataset3.csv',
 'data/AReM/cycling/dataset7.csv',
 'data/AReM/cycling/dataset6.csv',
 'data/AReM/cycling/dataset4.csv',
 'data/AReM/cycling/dataset5.csv',
 'data/AReM/cycling/dataset10.csv',
 'data/AReM/cycling/dataset11.csv',
 'data/AReM/cycling/dataset13.csv',
 'data/AReM/cycling/dataset12.csv',
 'data/AReM/cycling/dataset15.csv',
 'data/AReM/cycling/dataset14.csv',
 'data/AReM/cycling/dataset8.csv',
 'data/AReM/cycling/dataset9.csv',
 'data/AReM/lying/dataset7.csv',
 'data/AReM/lying/dataset6.csv',
 'data/AReM/lying/dataset4.csv',
 'data/AReM/lying/dataset5.csv',
 'data/AReM/lying/dataset10.csv',
 'data/AReM/lying/dataset11.csv',
 'data/AReM/lying/dataset13.csv',
 'data/AReM/lying/dataset12.csv',
 'data/AReM/lying/dataset15.csv',
 'data/AReM/lying/dataset14.csv',
 'data/AReM/lying/dataset8.csv',
 'data/AReM/lying/dataset9.csv',
 'data/AReM/sitting/dataset7.csv',
 'data/AReM/sitting/dataset6.csv',
 'data/AReM/sitting/dataset4.csv',
 'data/AReM/sitting/dataset5.csv',
 'data/AReM/sitting/dataset10.csv',
 'data/AReM/sitting/dataset11.csv',
 'data/AReM/sitting/dataset13.csv',
 'data/AReM/sitting/dataset12.csv',
 'data/AReM/sitting/dataset15.csv',
 'data/AReM/sitting/dataset14.csv',
 'data/AReM/sitting/dataset8.csv',
 'data/AReM/sitting/dataset9.csv',
 'data/AReM/standing/dataset7.csv',
 'data/AReM/standing/dataset6.csv',
 'data/AReM/standing/dataset4.csv',
 'data/AReM/standing/dataset5.csv',
 'data/AReM/standing/dataset10.csv',
 'data/AReM/standing/dataset11.csv',
 'data/AReM/standing/dataset13.csv',
 'data/AReM/standing/dataset12.csv',
 'data/AReM/standing/dataset15.csv',
 'data/AReM/standing/dataset14.csv',
 'data/AReM/standing/dataset8.csv',
 'data/AReM/standing/dataset9.csv',
 'data/AReM/walking/dataset7.csv',
 'data/AReM/walking/dataset6.csv',
 'data/AReM/walking/dataset4.csv',
 'data/AReM/walking/dataset5.csv',
 'data/AReM/walking/dataset10.csv',
 'data/AReM/walking/dataset11.csv',
 'data/AReM/walking/dataset13.csv',
 'data/AReM/walking/dataset12.csv',
 'data/AReM/walking/dataset15.csv',
 'data/AReM/walking/dataset14.csv',
 'data/AReM/walking/dataset8.csv',
 'data/AReM/walking/dataset9.csv']

In [6]:
testDfs = []
for f in testCsvs:
    dataFrame = pd.read_csv(f, skiprows = 4 , on_bad_lines='skip')
    testDfs.append(dataFrame)
testData = pd.concat(testDfs, axis = 0, ignore_index = True)

In [7]:
testData

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,39.25,0.43,22.75,0.43,33.75,1.30
1,250,39.25,0.43,23.00,0.00,33.00,0.00
2,500,39.25,0.43,23.25,0.43,33.00,0.00
3,750,39.50,0.50,23.00,0.71,33.00,0.00
4,1000,39.50,0.50,24.00,0.00,33.00,0.00
...,...,...,...,...,...,...,...
9115,118750,36.00,2.45,17.00,5.10,20.50,0.87
9116,119000,34.33,1.89,15.00,2.45,17.00,2.12
9117,119250,33.00,7.35,14.60,3.14,13.00,5.70
9118,119500,31.67,1.25,11.00,6.16,19.25,2.17
9119,119750,30.75,10.21,11.75,1.09,18.50,3.20

In [8]:
trainDfs = []
for f in trainCsvs:
    dataFrame = pd.read_csv(f, skiprows = 4 , on_bad_lines='skip')
    trainDfs.append(dataFrame)
trainData = pd.concat(trainDfs, axis = 0, ignore_index = True)

In [9]:
trainData

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,42.00,0.00,18.50,0.50,12.00,0.00
1,250,42.00,0.00,18.00,0.00,11.33,0.94
2,500,42.75,0.43,16.75,1.79,18.25,0.43
3,750,42.50,0.50,16.75,0.83,19.00,1.22
4,1000,43.00,0.82,16.25,0.83,18.00,0.00
...,...,...,...,...,...,...,...
33112,118750,31.50,1.66,12.50,3.20,14.25,4.44
33113,119000,27.33,1.25,11.33,0.94,20.00,4.00
33114,119250,37.80,7.68,14.20,2.48,17.25,0.83
33115,119500,33.75,1.30,15.75,5.21,16.50,2.69
33116,119750,32.67,3.09,18.67,0.47,14.00,3.16

# (c) Feature Extraction

# (i) Time-domain features usually used in time series classification

The features that are commonly used for time series classification are as follows:

Min: It is the minimum value in a dataset.

Max: It is the maximum value in a dataset.

Mean: It is the average of the values in a dataset.

Median: It is the middle value which divides the upper half and lower half of the dataset.

Standard Deviation: It is a measure of how dispersed the data is in relation to the mean.

1st Quartile: It the value under which 25% if the data points are found in a dataset.

3rd Quartile: It the value under which 75% if the data points are found in a dataset.

Interquartile Range: It is the range between 25% and 75%, where the middle 50% of the data points lie.

Range: It is the difference between the min and max values of a dataset.

Variance: It is mean squared difference between each data point and the centre of the distribution measured by the mean.

# (ii) Time-domain features for the data

In [10]:
cols = ['avg_rss12', 'var_rss12', 'avg_rss13', 'var_rss13', 'avg_rss23', 'var_rss23']

featuresList = []

for csvs in allCsvs:
    for c in csvs:
        
        dataFrame = pd.read_csv(c, skiprows = 4, usecols = cols ,on_bad_lines='skip')
        desc = dataFrame.describe().transpose().iloc[:, [3,7,1,5,2,4,6]]
        stats = []
        
        for i in range(6):
            for j in range(7):
                k = desc.iloc[i, j]
                stats.append(k)
        
        featuresList.append(stats)

columnNames = ['min1','max1','mean1','median1','std_dev1','1st Quartile1','3rd Quartile1',
              'min2','max2','mean2','median2','std_dev2','1st Quartile2','3rd Quartile2',
              'min3','max3','mean3','median3','std_dev3','1st Quartile3','3rd Quartile3',
              'min4','max4','mean4','median4','std_dev4','1st Quartile4','3rd Quartile4',
              'min5','max5','mean5','median5','std_dev5','1st Quartile5','3rd Quartile5',
              'min6','max6','mean6','median6','std_dev6','1st Quartile6','3rd Quartile6']

feats = pd.DataFrame(featuresList, columns = columnNames)
pd.set_option('display.max_columns', None)

In [11]:
feats

,min1,max1,mean1,median1,std_dev1,1st Quartile1,3rd Quartile1,min2,max2,mean2,median2,std_dev2,1st Quartile2,3rd Quartile2,min3,max3,mean3,median3,std_dev3,1st Quartile3,3rd Quartile3,min4,max4,mean4,median4,std_dev4,1st Quartile4,3rd Quartile4,min5,max5,mean5,median5,std_dev5,1st Quartile5,3rd Quartile5,min6,max6,mean6,median6,std_dev6,1st Quartile6,3rd Quartile6
0,37.25,45.00,40.624792,40.500,1.476967,39.25,42.0000,0.0,1.30,0.358604,0.430,0.322605,0.00,0.5000,4.00,29.50,19.040937,19.250,4.462952,16.00,23.2500,0.0,7.23,0.832542,0.500,0.965659,0.0000,1.1200,27.25,38.25,34.311292,35.00,2.188449,33.0000,36.00,0.0,1.92,0.570583,0.430,0.582915,0.00,1.3000
1,38.00,45.67,42.812812,42.500,1.435550,42.00,43.6700,0.0,1.22,0.372437,0.470,0.289158,0.00,0.5000,2.00,29.50,20.096979,21.000,3.893737,19.00,22.2500,0.0,5.76,0.876438,0.500,1.047259,0.0000,1.1450,27.67,38.50,33.024583,33.00,1.995255,32.0000,34.50,0.0,3.11,0.571083,0.430,0.601010,0.00,1.3000
2,35.00,47.40,43.954500,44.330,1.558835,43.00,45.0000,0.0,1.70,0.426250,0.470,0.338690,0.00,0.5000,6.50,29.75,22.122354,23.000,3.030943,19.75,24.0000,0.0,4.44,0.497312,0.430,0.550657,0.0000,0.8300,29.00,38.50,35.588458,36.00,1.999604,35.3625,36.50,0.0,1.79,0.493292,0.430,0.513506,0.00,0.9400
3,33.00,47.75,42.179812,43.500,3.670666,39.15,45.0000,0.0,3.00,0.696042,0.500,0.630860,0.00,1.1200,8.50,30.00,22.183625,23.000,3.810469,20.50,24.3725,0.0,5.15,0.989917,0.830,0.953730,0.4300,1.3000,20.00,38.67,33.493917,35.00,3.849448,30.4575,36.33,0.0,2.18,0.613521,0.500,0.524317,0.00,1.0000
4,33.00,45.75,41.678063,41.750,2.243490,41.33,42.7500,0.0,2.83,0.535979,0.500,0.405469,0.43,0.7100,3.00,28.25,19.006563,19.125,4.087107,16.50,22.0625,0.0,6.42,0.841875,0.500,0.928801,0.4300,1.1200,23.67,37.50,29.857083,30.00,2.411026,28.4575,31.25,0.0,1.79,0.383292,0.430,0.389164,0.00,0.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,20.75,46.25,34.763333,35.290,4.742208,31.67,38.2500,0.0,12.68,4.223792,3.900,2.278004,2.49,5.7225,5.00,23.75,15.239021,15.330,2.920829,13.50,17.2500,0.0,9.20,3.207062,3.000,1.590472,2.0500,4.1950,6.00,25.50,16.299563,16.25,3.174681,14.2500,18.33,0.0,9.39,3.288271,3.270,1.647528,2.05,4.3050
84,21.50,51.00,34.935812,35.500,4.645944,32.00,38.0625,0.0,12.21,4.115750,3.845,2.335243,2.35,5.6250,6.50,23.33,15.524521,15.500,2.900248,13.33,17.6700,0.0,9.09,3.092792,2.870,1.503446,2.0575,3.8400,6.33,25.00,15.997229,16.25,3.192058,14.2375,18.25,0.0,10.21,3.280021,3.015,1.700918,2.12,4.5000
85,18.33,47.67,34.333042,34.750,4.948770,31.25,38.0000,0.0,12.48,4.396958,3.900,2.568680,2.49,5.7450,7.67,23.33,15.562896,15.500,2.967741,13.67,17.5000,0.0,9.01,3.198313,2.930,1.676271,2.0500,4.2450,6.67,24.00,15.864437,16.00,3.000493,13.7500,18.00,0.0,8.01,3.261583,2.980,1.617290,2.05,4.3200
86,18.33,45.75,34.599875,35.125,4.731790,31.50,38.0000,0.0,15.37,4.398833,4.025,2.538521,2.55,5.7675,5.50,24.00,15.173667,15.000,3.036746,13.00,17.3725,0.0,9.18,3.145500,3.015,1.591346,2.0375,4.1575,6.50,23.25,16.055563,16.00,2.905688,14.0000,18.25,0.0,8.86,3.289542,3.015,1.680170,2.12,4.2600
87,15.50,43.67,34.225875,34.750,4.441798,31.25,37.2500,0.0,17.24,4.354500,3.900,2.518991,2.49,5.7650,7.67,23.00,15.606479,15.500,2.812274,13.75,17.5000,0.0,9.20,3.365375,3.030,1.730792,2.1200,4.4400,5.75,24.00,16.148000,16.25,2.992920,14.3300,18.25,0.0,9.42,3.479542,3.270,1.761146,2.24,4.5375

In [12]:
newValues = []
for i in range(1, 89):
    newValues.append(i)

feats.insert(loc = 0, column = 'Instance', value = newValues)

In [13]:
feats

,Instance,min1,max1,mean1,median1,std_dev1,1st Quartile1,3rd Quartile1,min2,max2,mean2,median2,std_dev2,1st Quartile2,3rd Quartile2,min3,max3,mean3,median3,std_dev3,1st Quartile3,3rd Quartile3,min4,max4,mean4,median4,std_dev4,1st Quartile4,3rd Quartile4,min5,max5,mean5,median5,std_dev5,1st Quartile5,3rd Quartile5,min6,max6,mean6,median6,std_dev6,1st Quartile6,3rd Quartile6
0,1,37.25,45.00,40.624792,40.500,1.476967,39.25,42.0000,0.0,1.30,0.358604,0.430,0.322605,0.00,0.5000,4.00,29.50,19.040937,19.250,4.462952,16.00,23.2500,0.0,7.23,0.832542,0.500,0.965659,0.0000,1.1200,27.25,38.25,34.311292,35.00,2.188449,33.0000,36.00,0.0,1.92,0.570583,0.430,0.582915,0.00,1.3000
1,2,38.00,45.67,42.812812,42.500,1.435550,42.00,43.6700,0.0,1.22,0.372437,0.470,0.289158,0.00,0.5000,2.00,29.50,20.096979,21.000,3.893737,19.00,22.2500,0.0,5.76,0.876438,0.500,1.047259,0.0000,1.1450,27.67,38.50,33.024583,33.00,1.995255,32.0000,34.50,0.0,3.11,0.571083,0.430,0.601010,0.00,1.3000
2,3,35.00,47.40,43.954500,44.330,1.558835,43.00,45.0000,0.0,1.70,0.426250,0.470,0.338690,0.00,0.5000,6.50,29.75,22.122354,23.000,3.030943,19.75,24.0000,0.0,4.44,0.497312,0.430,0.550657,0.0000,0.8300,29.00,38.50,35.588458,36.00,1.999604,35.3625,36.50,0.0,1.79,0.493292,0.430,0.513506,0.00,0.9400
3,4,33.00,47.75,42.179812,43.500,3.670666,39.15,45.0000,0.0,3.00,0.696042,0.500,0.630860,0.00,1.1200,8.50,30.00,22.183625,23.000,3.810469,20.50,24.3725,0.0,5.15,0.989917,0.830,0.953730,0.4300,1.3000,20.00,38.67,33.493917,35.00,3.849448,30.4575,36.33,0.0,2.18,0.613521,0.500,0.524317,0.00,1.0000
4,5,33.00,45.75,41.678063,41.750,2.243490,41.33,42.7500,0.0,2.83,0.535979,0.500,0.405469,0.43,0.7100,3.00,28.25,19.006563,19.125,4.087107,16.50,22.0625,0.0,6.42,0.841875,0.500,0.928801,0.4300,1.1200,23.67,37.50,29.857083,30.00,2.411026,28.4575,31.25,0.0,1.79,0.383292,0.430,0.389164,0.00,0.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,20.75,46.25,34.763333,35.290,4.742208,31.67,38.2500,0.0,12.68,4.223792,3.900,2.278004,2.49,5.7225,5.00,23.75,15.239021,15.330,2.920829,13.50,17.2500,0.0,9.20,3.207062,3.000,1.590472,2.0500,4.1950,6.00,25.50,16.299563,16.25,3.174681,14.2500,18.33,0.0,9.39,3.288271,3.270,1.647528,2.05,4.3050
84,85,21.50,51.00,34.935812,35.500,4.645944,32.00,38.0625,0.0,12.21,4.115750,3.845,2.335243,2.35,5.6250,6.50,23.33,15.524521,15.500,2.900248,13.33,17.6700,0.0,9.09,3.092792,2.870,1.503446,2.0575,3.8400,6.33,25.00,15.997229,16.25,3.192058,14.2375,18.25,0.0,10.21,3.280021,3.015,1.700918,2.12,4.5000
85,86,18.33,47.67,34.333042,34.750,4.948770,31.25,38.0000,0.0,12.48,4.396958,3.900,2.568680,2.49,5.7450,7.67,23.33,15.562896,15.500,2.967741,13.67,17.5000,0.0,9.01,3.198313,2.930,1.676271,2.0500,4.2450,6.67,24.00,15.864437,16.00,3.000493,13.7500,18.00,0.0,8.01,3.261583,2.980,1.617290,2.05,4.3200
86,87,18.33,45.75,34.599875,35.125,4.731790,31.50,38.0000,0.0,15.37,4.398833,4.025,2.538521,2.55,5.7675,5.50,24.00,15.173667,15.000,3.036746,13.00,17.3725,0.0,9.18,3.145500,3.015,1.591346,2.0375,4.1575,6.50,23.25,16.055563,16.00,2.905688,14.0000,18.25,0.0,8.86,3.289542,3.015,1.680170,2.12,4.2600
87,88,15.50,43.67,34.225875,34.750,4.441798,31.25,37.2500,0.0,17.24,4.354500,3.900,2.518991,2.49,5.7650,7.67,23.00,15.606479,15.500,2.812274,13.75,17.5000,0.0,9.20,3.365375,3.030,1.730792,2.1200,4.4400,5.75,24.00,16.148000,16.25,2.992920,14.3300,18.25,0.0,9.42,3.479542,3.270,1.761146,2.24,4.5375

# (iii) Standard Deviation of time-domain features and 90% bootstrap confidence interval

In [14]:
intermediateData = feats.iloc[:, 1:]
k = intermediateData.describe().transpose()

In [15]:
k

,count,mean,std,min,25%,50%,75%,max
min1,87.0,29.054368,9.624011,0.000000,21.750000,28.750000,36.290000,48.000000
max1,87.0,45.616437,4.207745,30.000000,44.670000,45.750000,47.750000,56.250000
mean1,87.0,39.021212,5.276431,24.562958,34.904521,39.433792,43.067146,48.004167
median1,87.0,38.958506,5.386624,24.250000,35.500000,39.500000,43.250000,48.000000
std_dev1,87.0,3.009985,1.771282,0.032038,1.488923,3.226507,4.573261,7.684146
1st Quartile1,87.0,37.112011,6.127846,23.187500,31.710000,39.250000,42.000000,48.000000
3rd Quartile1,87.0,41.322816,5.031028,26.500000,38.250000,40.250000,45.000000,54.000000
min2,87.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max2,87.0,6.350920,5.059656,0.430000,1.790000,4.500000,11.020000,17.240000
mean2,87.0,1.472942,1.577908,0.007167,0.369573,0.492563,2.733010,4.576562
median2,87.0,1.302874,1.413545,0.000000,0.430000,0.500000,2.200000,4.260000
std_dev2,87.0,0.995638,0.885875,0.055106,0.325706,0.464541,1.908381,2.625516
1st Quartile2,87.0,0.753966,0.948434,0.000000,0.000000,0.430000,1.300000,2.870000
3rd Quartile2,87.0,1.993391,2.131337,0.000000,0.500000,0.500000,3.792500,6.105000
min3,87.0,3.137126,2.954516,0.000000,0.000000,2.500000,6.000000,8.500000
max3,87.0,22.906437,4.819848,11.330000,21.125000,23.500000,25.830000,35.000000
mean3,87.0,14.348482,3.976754,4.382208,12.792323,15.302625,16.531083,22.183625
median3,87.0,14.680747,4.009687,4.500000,12.875000,15.330000,16.710000,23.000000
std_dev3,87.0,3.579929,0.952011,1.745801,2.937925,3.468655,3.987098,7.638935
1st Quartile3,87.0,12.186667,4.184148,2.500000,10.460000,13.250000,14.250000,20.500000
3rd Quartile3,87.0,16.796753,4.153451,6.000000,15.031250,17.670000,19.000000,24.372500
min4,87.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max4,87.0,6.787931,2.181809,2.490000,5.170000,6.120000,9.000000,11.420000
mean4,87.0,1.513224,1.168268,0.332062,0.622687,0.841875,2.997146,3.365375
median4,87.0,1.323046,1.148591,0.000000,0.470000,0.500000,2.860000,3.200000
std_dev4,87.0,1.071990,0.458612,0.409145,0.718283,0.904436,1.600137,1.861730
1st Quartile4,87.0,0.727299,0.844919,0.000000,0.000000,0.430000,1.711250,2.170000
3rd Quartile4,87.0,2.013736,1.555235,0.470000,0.830000,1.120000,4.015000,4.440000
min5,87.0,4.603678,6.121205,0.000000,0.000000,2.500000,6.750000,29.000000
max5,87.0,24.332414,5.773355,12.000000,21.000000,23.500000,25.500000,40.330000
mean5,87.0,16.011230,5.704025,4.303979,13.387896,15.989167,17.223000,35.588458
median5,87.0,16.219368,5.844368,2.250000,13.395000,16.000000,17.710000,36.000000
std_dev5,87.0,3.558347,1.012358,1.995255,2.962039,3.268502,4.074511,7.853427
1st Quartile5,87.0,13.790287,6.122142,1.000000,11.280000,14.000000,15.250000,35.362500
3rd Quartile5,87.0,18.522787,5.563553,5.542500,16.595000,18.250000,20.750000,36.500000
min6,87.0,0.004943,0.046101,0.000000,0.000000,0.000000,0.000000,0.430000
max6,87.0,6.462644,2.533515,1.790000,4.500000,6.260000,8.780000,13.610000
mean6,87.0,1.631250,1.157222,0.383292,0.734271,0.933000,3.026708,3.530500
median6,87.0,1.453966,1.089858,0.430000,0.500000,0.830000,2.640000,3.340000
std_dev6,87.0,1.055055,0.516968,0.388372,0.618111,0.842087,1.643885,1.963685
1st Quartile6,87.0,0.906983,0.761542,0.000000,0.430000,0.470000,1.680000,2.240000
3rd Quartile6,87.0,2.156437,1.526871,0.500000,1.000000,1.220000,4.048750,4.617500

In [16]:
standardDevData = k.loc[:, 'std']
standardDev = pd.DataFrame(standardDevData)

In [17]:
standardDev

                    std
min1           9.624011
max1           4.207745
mean1          5.276431
median1        5.386624
std_dev1       1.771282
1st Quartile1  6.127846
3rd Quartile1  5.031028
min2           0.000000
max2           5.059656
mean2          1.577908
median2        1.413545
std_dev2       0.885875
1st Quartile2  0.948434
3rd Quartile2  2.131337
min3           2.954516
max3           4.819848
mean3          3.976754
median3        4.009687
std_dev3       0.952011
1st Quartile3  4.184148
3rd Quartile3  4.153451
min4           0.000000
max4           2.181809
mean4          1.168268
median4        1.148591
std_dev4       0.458612
1st Quartile4  0.844919
3rd Quartile4  1.555235
min5           6.121205
max5           5.773355
mean5          5.704025
median5        5.844368
std_dev5       1.012358
1st Quartile5  6.122142
3rd Quartile5  5.563553
min6           0.046101
max6           2.533515
mean6          1.157222
median6        1.089858
std_dev6       0.516968
1st Quartile6  0.761542
3rd Quartile6  1.526871

In [18]:
standardDev.reset_index(inplace = True)
standardDev.columns = ['Feature Name', 'Standard Deviation']

In [19]:
standardDev

     Feature Name  Standard Deviation
0            min1            9.624011
1            max1            4.207745
2           mean1            5.276431
3         median1            5.386624
4        std_dev1            1.771282
5   1st Quartile1            6.127846
6   3rd Quartile1            5.031028
7            min2            0.000000
8            max2            5.059656
9           mean2            1.577908
10        median2            1.413545
11       std_dev2            0.885875
12  1st Quartile2            0.948434
13  3rd Quartile2            2.131337
14           min3            2.954516
15           max3            4.819848
16          mean3            3.976754
17        median3            4.009687
18       std_dev3            0.952011
19  1st Quartile3            4.184148
20  3rd Quartile3            4.153451
21           min4            0.000000
22           max4            2.181809
23          mean4            1.168268
24        median4            1.148591
25       std_dev4            0.458612
26  1st Quartile4            0.844919
27  3rd Quartile4            1.555235
28           min5            6.121205
29           max5            5.773355
30          mean5            5.704025
31        median5            5.844368
32       std_dev5            1.012358
33  1st Quartile5            6.122142
34  3rd Quartile5            5.563553
35           min6            0.046101
36           max6            2.533515
37          mean6            1.157222
38        median6            1.089858
39       std_dev6            0.516968
40  1st Quartile6            0.761542
41  3rd Quartile6            1.526871

In [20]:
confInt = []

for c in range(len(columnNames)):
    
    d = feats.iloc[:, c + 1]
    d1 = np.array(d)
    d1 = d1[~np.isnan(d1)]
    res = bs.bootstrap(d1, stat_func = bs_stats.mean, alpha = 0.1)
    l = []
    l.append(columnNames[c])
    l.append(d.std())
    l.append(res.lower_bound)
    l.append(res.upper_bound)
    confInt.append(l)

bootstrapped = pd.DataFrame(confInt, columns = ['Features', 'Standard Deviation', 'Lower Bound', 'Upper Bound'])

In [21]:
bootstrapped

         Features  Standard Deviation  Lower Bound  Upper Bound
0            min1            9.624011    27.370201    30.763270
1            max1            4.207745    44.889655    46.369109
2           mean1            5.276431    38.097046    39.949501
3         median1            5.386624    38.011658    39.906460
4        std_dev1            1.771282     2.694809     3.317570
5   1st Quartile1            6.127846    36.043849    38.195990
6   3rd Quartile1            5.031028    40.433181    42.222812
7            min2            0.000000     0.000000     0.000000
8            max2            5.059656     5.476770     7.252080
9           mean2            1.577908     1.190479     1.742951
10        median2            1.413545     1.052466     1.541437
11       std_dev2            0.885875     0.843433     1.149474
12  1st Quartile2            0.948434     0.583213     0.913534
13  3rd Quartile2            2.131337     1.607843     2.346764
14           min3            2.954516     2.614356     3.669885
15           max3            4.819848    22.062684    23.751155
16          mean3            3.976754    13.661830    15.051473
17        median3            4.009687    13.985977    15.387256
18       std_dev3            0.952011     3.408128     3.741047
19  1st Quartile3            4.184148    11.470786    12.922935
20  3rd Quartile3            4.153451    16.086078    17.516897
21           min4            0.000000     0.000000     0.000000
22           max4            2.181809     6.403098     7.170920
23          mean4            1.168268     1.302359     1.713785
24        median4            1.148591     1.115227     1.522532
25       std_dev4            0.458612     0.991321     1.151554
26  1st Quartile4            0.844919     0.573560     0.873595
27  3rd Quartile4            1.555235     1.742526     2.282795
28           min5            6.121205     3.508592     5.617977
29           max5            5.773355    23.287414    25.325902
30          mean5            5.704025    15.003717    16.983693
31        median5            5.844368    15.167730    17.212267
32       std_dev5            1.012358     3.375884     3.732333
33  1st Quartile5            6.122142    12.707813    14.809010
34  3rd Quartile5            5.563553    17.519654    19.457348
35           min6            0.046101    -0.004943     0.009885
36           max6            2.533515     6.023678     6.898167
37          mean6            1.157222     1.424547     1.829756
38        median6            1.089858     1.260632     1.641210
39       std_dev6            0.516968     0.961339     1.144677
40  1st Quartile6            0.761542     0.772902     1.037185
41  3rd Quartile6            1.526871     1.882056     2.423397

# (iv) Three most important time-domain features

According to me the three most important time-domain features are:

Mean: Because it contains the score of each observation in the dataset and is good measure of the central tendency of the data when distribution is continuous.

Median: It provides us the central value of the dataset and gives us an idea of the central tendency of the dataset and is an important metric when we have outliers and skewed data in the dataset.

Standard Deviation: It gives us an ideal measure of dispersion of the data.

# 2. ISLR 3.7.4

(a) Although, the true relationship between X and Y is linear the 'cubic' regression model might fit the training the training data really well as it has more flexibility and hence, the training RSS might be 'lower' for the cubic regression model compared to the linear one.

(b) As we do not have enough information about the testing data, we cannot conclude anything perfectly. However, since the true relationship between X and Y is linear it will have lower RSS as compared to the cubic regression model as it will overfit the data and would result is higher RSS error.

(c) The train RSS for the cubic regression model might be lower than the train RSS for the linear model as the true relationship is non-linear, the cubic regression will fit better than the lienar regression model.

(d) As there is not enough information to let us know how far the true relationship between X and Y is from a linear relationship. If the relationship is closer to the linear regression then the test RSS for it would be lower than the test RSS for the cubic regression. However, if it is closer to the cubic regression than the linear regression then the test RSS for the cubic regression would be lower. Hence, we cannot conclusively state which regression will have a lower test RSS.